///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ImageValidation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ImageValidationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ac334153-6baa-4f41-861e-7fa7eba068d5")]
    public partial class ImageValidationRepository : RepoGenBaseFolder
    {
        static ImageValidationRepository instance = new ImageValidationRepository();
        ImageValidationRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the ImageValidationRepository element repository.
        /// </summary>
        [RepositoryFolder("ac334153-6baa-4f41-861e-7fa7eba068d5")]
        public static ImageValidationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ImageValidationRepository() 
            : base("ImageValidationRepository", "/", null, 0, false, "ac334153-6baa-4f41-861e-7fa7eba068d5", ".\\RepositoryImages\\ImageValidationRepositoryac334153.rximgres")
        {
            _rxmainframe = new ImageValidationRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ac334153-6baa-4f41-861e-7fa7eba068d5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("ad06defc-1d2f-403b-98d2-e1e5d050c808")]
        public virtual ImageValidationRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ImageValidationRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("ad06defc-1d2f-403b-98d2-e1e5d050c808")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _chkshowimageInfo;
            TheCatInfoClass _thecatInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, true, true, "ad06defc-1d2f-403b-98d2-e1e5d050c808", "")
            {
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", "", 30000, null, "e21d0a8c-4c21-40d7-b93f-2d7fb62a97bc");
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", "?/?/tabpage[@controlname='RxTabImageBased']/checkbox[@controlname='chkShowImage']", "", 30000, null, "a69d5e6e-6c86-47c4-af5d-bae233b05ff3");
                _thecatInfo = new TheCatInfoClass(this);
            }

            /// <summary>
            /// The TheCatInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("fd195e45-457c-464c-8b9e-8c2ae38f52bf")]
            public class TheCatInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TheCatInfoClass class constructor.
                /// </summary>
                public TheCatInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TheCat", "?/?/tabpage[@controlname='RxTabImageBased']/picture[@controlname='TheCat']", 30000, null, "fd195e45-457c-464c-8b9e-8c2ae38f52bf")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("7e9f37e5-62d8-4952-b94b-304819b8c187")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("7e9f37e5-62d8-4952-b94b-304819b8c187");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7e9f37e5-62d8-4952-b94b-304819b8c187")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7e9f37e5-62d8-4952-b94b-304819b8c187", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ad06defc-1d2f-403b-98d2-e1e5d050c808")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad06defc-1d2f-403b-98d2-e1e5d050c808")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("e21d0a8c-4c21-40d7-b93f-2d7fb62a97bc")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("e21d0a8c-4c21-40d7-b93f-2d7fb62a97bc")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("a69d5e6e-6c86-47c4-af5d-bae233b05ff3")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("a69d5e6e-6c86-47c4-af5d-bae233b05ff3")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("fd195e45-457c-464c-8b9e-8c2ae38f52bf")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("fd195e45-457c-464c-8b9e-8c2ae38f52bf")]
            public virtual TheCatInfoClass TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
